package com.nsemcx.trading.controller;

import com.nsemcx.trading.agent.OrchestratorAgent;
import com.nsemcx.trading.event.ApiResponse;
import com.nsemcx.trading.event.MarketDashboard;
import com.nsemcx.trading.model.FundamentalData;
import com.nsemcx.trading.repository.FundamentalDataRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

/**
 * REST endpoints for the market dashboard.
 * Base path: /api/dashboard
 */
@Slf4j
@RestController
@RequestMapping("/api/dashboard")
@RequiredArgsConstructor
public class DashboardController {

    private final OrchestratorAgent orchestratorAgent;
    private final FundamentalDataRepository fundamentalDataRepository;

    /**
     * GET /api/dashboard
     * Returns the full market dashboard snapshot generated by the OrchestratorAgent.
     */
    @GetMapping
    public ResponseEntity<ApiResponse<MarketDashboard>> getDashboard() {
        try {
            MarketDashboard dashboard = orchestratorAgent.generateDashboard();
            return ResponseEntity.ok(ApiResponse.ok(dashboard, "Market dashboard generated"));
        } catch (Exception ex) {
            log.error("Dashboard generation failed: {}", ex.getMessage(), ex);
            return ResponseEntity.ok(ApiResponse.error("Dashboard generation failed: " + ex.getMessage()));
        }
    }

    /**
     * GET /api/dashboard/sentiment
     * Returns only the market sentiment score and label.
     */
    @GetMapping("/sentiment")
    public ResponseEntity<ApiResponse<Map<String, Object>>> getSentiment() {
        try {
            MarketDashboard dashboard = orchestratorAgent.generateDashboard();
            Map<String, Object> sentiment = Map.of(
                    "sentimentScore", dashboard.marketSentimentScore(),
                    "sentiment", dashboard.marketSentiment() != null ? dashboard.marketSentiment() : deriveSentimentLabel(dashboard.marketSentimentScore()),
                    "isBullish", dashboard.isBullishMarket(),
                    "isBearish", dashboard.isBearishMarket(),
                    "analysisDate", dashboard.analysisDate(),
                    "generatedAt", dashboard.generatedAt()
            );
            return ResponseEntity.ok(ApiResponse.ok(sentiment, "Market sentiment data"));
        } catch (Exception ex) {
            log.error("Sentiment fetch failed: {}", ex.getMessage(), ex);
            return ResponseEntity.ok(ApiResponse.error("Sentiment fetch failed: " + ex.getMessage()));
        }
    }

    /**
     * GET /api/dashboard/sectors
     * Returns sector leaders and laggards.
     */
    @GetMapping("/sectors")
    public ResponseEntity<ApiResponse<MarketDashboard.SectorAnalysis>> getSectors() {
        try {
            MarketDashboard dashboard = orchestratorAgent.generateDashboard();
            MarketDashboard.SectorAnalysis sectors = dashboard.sectorAnalysis();
            if (sectors == null) {
                return ResponseEntity.ok(ApiResponse.error("Sector data not available"));
            }
            return ResponseEntity.ok(ApiResponse.ok(sectors, "Sector performance data"));
        } catch (Exception ex) {
            log.error("Sector data fetch failed: {}", ex.getMessage(), ex);
            return ResponseEntity.ok(ApiResponse.error("Sector data fetch failed: " + ex.getMessage()));
        }
    }

    /**
     * GET /api/dashboard/flow
     * Returns FII/DII institutional flow data.
     */
    @GetMapping("/flow")
    public ResponseEntity<ApiResponse<MarketDashboard.InstitutionalFlow>> getFlow() {
        try {
            MarketDashboard dashboard = orchestratorAgent.generateDashboard();
            MarketDashboard.InstitutionalFlow flow = dashboard.institutionalFlow();
            if (flow == null) {
                // Fallback: return from fundamental data repository
                List<FundamentalData> data = fundamentalDataRepository.findPositiveFiiFlow();
                BigDecimal totalFii = data.stream()
                        .map(FundamentalData::getFiiFlow)
                        .filter(f -> f != null)
                        .reduce(BigDecimal.ZERO, BigDecimal::add);
                BigDecimal totalDii = data.stream()
                        .map(FundamentalData::getDiiFlow)
                        .filter(f -> f != null)
                        .reduce(BigDecimal.ZERO, BigDecimal::add);

                flow = new MarketDashboard.InstitutionalFlow(
                        totalFii.doubleValue(), totalDii.doubleValue(),
                        0, 0, java.time.LocalDate.now(),
                        "Aggregated from fundamental data", "MIXED");
            }
            return ResponseEntity.ok(ApiResponse.ok(flow, "Institutional flow data"));
        } catch (Exception ex) {
            log.error("Flow data fetch failed: {}", ex.getMessage(), ex);
            return ResponseEntity.ok(ApiResponse.error("Flow data fetch failed: " + ex.getMessage()));
        }
    }

    /**
     * GET /api/dashboard/vix
     * Returns India VIX proxy and volatility outlook.
     */
    @GetMapping("/vix")
    public ResponseEntity<ApiResponse<MarketDashboard.VixOutlook>> getVix() {
        try {
            MarketDashboard dashboard = orchestratorAgent.generateDashboard();
            MarketDashboard.VixOutlook vix = dashboard.vixOutlook();
            if (vix == null) {
                return ResponseEntity.ok(ApiResponse.error("VIX data not available"));
            }
            return ResponseEntity.ok(ApiResponse.ok(vix, "India VIX outlook"));
        } catch (Exception ex) {
            log.error("VIX data fetch failed: {}", ex.getMessage(), ex);
            return ResponseEntity.ok(ApiResponse.error("VIX data fetch failed: " + ex.getMessage()));
        }
    }

    // ── Helper ────────────────────────────────────────────────────────────────

    private String deriveSentimentLabel(double score) {
        if (score >= 75) return "STRONGLY_BULLISH";
        if (score >= 60) return "BULLISH";
        if (score >= 45) return "NEUTRAL";
        if (score >= 30) return "BEARISH";
        return "STRONGLY_BEARISH";
    }
}
