package com.nsemcx.trading.service;

import com.nsemcx.trading.config.TradingProperties;
import com.nsemcx.trading.model.ForwardTestResult;
import com.nsemcx.trading.model.ForwardTestResult.PredictionDirection;
import com.nsemcx.trading.model.Instrument;
import com.nsemcx.trading.model.TradeSignal;
import com.nsemcx.trading.repository.ForwardTestRepository;
import com.nsemcx.trading.repository.InstrumentRepository;
import com.nsemcx.trading.repository.MarketDataRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Objects;

/**
 * Manages forward-testing (walk-forward analysis) by:
 * <ol>
 *   <li>Recording a prediction at signal time.</li>
 *   <li>Evaluating that prediction once {@code lookAheadDays} have elapsed.</li>
 *   <li>Generating an accuracy report per instrument or globally.</li>
 * </ol>
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ForwardTestingService {

    private final ForwardTestRepository forwardTestRepository;
    private final MarketDataRepository marketDataRepository;
    private final InstrumentRepository instrumentRepository;
    private final TradingProperties tradingProperties;

    // ── DTOs ─────────────────────────────────────────────────────────────────

    /**
     * Accuracy report aggregated per instrument (or globally when instrumentId is null).
     */
    public record ForwardTestAccuracy(
            Long instrumentId,
            String symbol,
            long totalPredictions,
            long evaluatedPredictions,
            long pendingEvaluation,
            long correctPredictions,
            double overallAccuracyPct,
            double bullishAccuracyPct,
            double bearishAccuracyPct,
            double neutralAccuracyPct,
            BigDecimal avgConfidenceWhenCorrect,
            BigDecimal avgConfidenceWhenWrong
    ) {
        public boolean hasSufficientData() {
            return evaluatedPredictions >= 10;
        }

        public String grade() {
            if (!hasSufficientData()) return "INSUFFICIENT_DATA";
            if (overallAccuracyPct >= 65) return "EXCELLENT";
            if (overallAccuracyPct >= 55) return "GOOD";
            if (overallAccuracyPct >= 45) return "FAIR";
            return "POOR";
        }
    }

    // ── Record prediction ─────────────────────────────────────────────────────

    /**
     * Records a new forward-test prediction from a trade signal.
     * Called immediately after a signal is generated by the agent pipeline.
     *
     * @param signal the freshly generated signal
     * @return the persisted ForwardTestResult (with wasCorrect = null)
     */
    @Transactional
    public ForwardTestResult recordPrediction(TradeSignal signal) {
        TradingProperties.ForwardTesting cfg = tradingProperties.forwardTesting();
        if (!cfg.enabled()) {
            return null;
        }

        PredictionDirection direction = mapSignalToDirection(signal);
        if (direction == PredictionDirection.NEUTRAL) {
            // Only record directional predictions
            log.debug("Skipping forward-test recording for neutral signal id={}", signal.getId());
            return null;
        }

        BigDecimal target = signal.getTarget1() != null ? signal.getTarget1()
                : (signal.getTarget2() != null ? signal.getTarget2() : null);

        BigDecimal confidence = signal.getConfidence();

        ForwardTestResult result = ForwardTestResult.builder()
                .signal(signal)
                .instrument(signal.getInstrument())
                .predictionDate(LocalDate.now())
                .lookAheadDays(cfg.lookAheadDays())
                .predictedDirection(direction)
                .predictedTarget(target)
                .confidenceScore(confidence)
                .build();

        result = forwardTestRepository.save(result);
        log.info("Recorded forward-test prediction: id={}, instrument={}, direction={}, lookAhead={}d",
                result.getId(), signal.getInstrument().getSymbol(), direction, cfg.lookAheadDays());
        return result;
    }

    // ── Scheduled evaluation ──────────────────────────────────────────────────

    /**
     * Runs daily (configurable via cron) to evaluate pending predictions
     * whose look-ahead period has elapsed. Fetches actual market price and
     * marks wasCorrect = true/false.
     */
    @Scheduled(cron = "${trading.scheduler.forward-test-eval-cron:0 0 18 * * MON-FRI}")
    @Transactional
    public void evaluatePredictions() {
        LocalDate today = LocalDate.now();
        // A prediction is ready when predictionDate + lookAheadDays <= today
        List<ForwardTestResult> pending = forwardTestRepository.findPendingEvaluation(today);

        if (pending.isEmpty()) {
            log.debug("No forward-test predictions ready for evaluation today");
            return;
        }

        log.info("Evaluating {} pending forward-test predictions", pending.size());
        int evaluated = 0;

        for (ForwardTestResult prediction : pending) {
            try {
                evaluateSinglePrediction(prediction, today);
                evaluated++;
            } catch (Exception ex) {
                log.error("Failed to evaluate forward-test id={}: {}", prediction.getId(), ex.getMessage());
            }
        }

        log.info("Forward-test evaluation complete: {}/{} predictions evaluated", evaluated, pending.size());
    }

    private void evaluateSinglePrediction(ForwardTestResult prediction, LocalDate today) {
        LocalDate evalDate = prediction.getPredictionDate().plusDays(prediction.getLookAheadDays());
        if (evalDate.isAfter(today)) return; // not yet due

        Instrument instrument = prediction.getInstrument();

        // Fetch market data closest to evaluation date
        OffsetDateTime evalStart = evalDate.atStartOfDay().atOffset(ZoneOffset.UTC);
        OffsetDateTime evalEnd = evalDate.plusDays(5).atStartOfDay().atOffset(ZoneOffset.UTC);

        List<?> recentData = marketDataRepository.findByInstrumentIdAndDateRange(
                instrument.getId(), evalStart, evalEnd);

        if (recentData.isEmpty()) {
            log.debug("No market data available to evaluate forward-test id={} at {}", prediction.getId(), evalDate);
            return;
        }

        // Use the first available close after evaluation date
        var latestOpt = marketDataRepository.findLatestByInstrumentId(instrument.getId());
        if (latestOpt.isEmpty()) return;

        BigDecimal actualPrice = latestOpt.get().getClose();

        // Determine actual direction vs prediction date price
        var predictionDayDataOpt = marketDataRepository.findByInstrumentIdAndDateRange(
                instrument.getId(),
                prediction.getPredictionDate().atStartOfDay().atOffset(ZoneOffset.UTC),
                prediction.getPredictionDate().plusDays(1).atStartOfDay().atOffset(ZoneOffset.UTC));

        if (predictionDayDataOpt.isEmpty()) return;

        var predDayData = marketDataRepository.findLatestByInstrumentId(instrument.getId()).orElse(null);
        if (predDayData == null) return;

        BigDecimal predictionDayPrice = predDayData.getClose();
        int comparison = actualPrice.compareTo(predictionDayPrice);

        PredictionDirection actualDirection = comparison > 0 ? PredictionDirection.BULLISH
                : comparison < 0 ? PredictionDirection.BEARISH
                : PredictionDirection.NEUTRAL;

        boolean wasCorrect = prediction.getPredictedDirection() == actualDirection;

        prediction.setActualPrice(actualPrice);
        prediction.setActualDirection(actualDirection);
        prediction.setWasCorrect(wasCorrect);
        forwardTestRepository.save(prediction);

        log.debug("Evaluated forward-test id={}: predicted={}, actual={}, correct={}",
                prediction.getId(), prediction.getPredictedDirection(), actualDirection, wasCorrect);
    }

    // ── Accuracy reports ──────────────────────────────────────────────────────

    /**
     * Returns a per-instrument accuracy report.
     *
     * @param instrumentId instrument to analyse
     * @return ForwardTestAccuracy record
     */
    @Transactional(readOnly = true)
    public ForwardTestAccuracy getAccuracyReport(Long instrumentId) {
        Instrument instrument = instrumentRepository.findById(instrumentId)
                .orElseThrow(() -> new IllegalArgumentException("Instrument not found: " + instrumentId));

        long total = forwardTestRepository.findByInstrumentIdOrderByPredictionDateDesc(instrumentId).size();
        long evaluated = forwardTestRepository.countEvaluatedByInstrumentId(instrumentId);
        long correct = forwardTestRepository.countCorrectByInstrumentId(instrumentId);
        long pending = total - evaluated;

        double overallAccuracy = evaluated > 0 ? (double) correct / evaluated * 100 : 0;

        long bullishTotal = forwardTestRepository.countByInstrumentIdAndDirection(instrumentId, PredictionDirection.BULLISH);
        long bullishCorrect = forwardTestRepository.countCorrectByInstrumentIdAndDirection(instrumentId, PredictionDirection.BULLISH);
        long bearishTotal = forwardTestRepository.countByInstrumentIdAndDirection(instrumentId, PredictionDirection.BEARISH);
        long bearishCorrect = forwardTestRepository.countCorrectByInstrumentIdAndDirection(instrumentId, PredictionDirection.BEARISH);
        long neutralTotal = forwardTestRepository.countByInstrumentIdAndDirection(instrumentId, PredictionDirection.NEUTRAL);
        long neutralCorrect = forwardTestRepository.countCorrectByInstrumentIdAndDirection(instrumentId, PredictionDirection.NEUTRAL);

        double bullishAcc = bullishTotal > 0 ? (double) bullishCorrect / bullishTotal * 100 : 0;
        double bearishAcc = bearishTotal > 0 ? (double) bearishCorrect / bearishTotal * 100 : 0;
        double neutralAcc = neutralTotal > 0 ? (double) neutralCorrect / neutralTotal * 100 : 0;

        Double avgConfCorrect = forwardTestRepository.findAvgConfidenceWhenCorrect(instrumentId);

        return new ForwardTestAccuracy(
                instrumentId,
                instrument.getSymbol(),
                total, evaluated, pending, correct,
                round(overallAccuracy), round(bullishAcc), round(bearishAcc), round(neutralAcc),
                avgConfCorrect != null ? BigDecimal.valueOf(avgConfCorrect).setScale(2, RoundingMode.HALF_UP) : BigDecimal.ZERO,
                BigDecimal.ZERO  // avgConfidenceWhenWrong requires additional query
        );
    }

    /**
     * Returns a global accuracy report across all instruments.
     */
    @Transactional(readOnly = true)
    public ForwardTestAccuracy getGlobalAccuracyReport() {
        long total = forwardTestRepository.count();
        long evaluated = forwardTestRepository.countAllEvaluated();
        long correct = forwardTestRepository.countAllCorrect();
        long pending = total - evaluated;
        double accuracy = evaluated > 0 ? (double) correct / evaluated * 100 : 0;

        return new ForwardTestAccuracy(
                null, "ALL",
                total, evaluated, pending, correct,
                round(accuracy), 0, 0, 0,
                BigDecimal.ZERO, BigDecimal.ZERO
        );
    }

    /**
     * Returns the most recent predictions (with or without outcomes).
     */
    @Transactional(readOnly = true)
    public List<ForwardTestResult> getRecentPredictions(int limit) {
        return forwardTestRepository.findRecent(Math.min(limit, 200));
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private PredictionDirection mapSignalToDirection(TradeSignal signal) {
        if (signal.getSignalType() == null) return PredictionDirection.NEUTRAL;
        return switch (signal.getSignalType()) {
            case STRONG_BUY, BUY, WEAK_BUY, CALL_BUY -> PredictionDirection.BULLISH;
            case STRONG_SELL, SELL, WEAK_SELL, PUT_BUY -> PredictionDirection.BEARISH;
            default -> PredictionDirection.NEUTRAL;
        };
    }

    private double round(double value) {
        return BigDecimal.valueOf(value).setScale(2, RoundingMode.HALF_UP).doubleValue();
    }
}
